### ISSUE TITLE
Someone help me

### ISSUE THREAD

**Issue by SoundDr0ut** [SealedSaucer/Online-Forever#31]
PS C:\Users\sixpa\Downloads\Compressed\Online-Forever-main> python filename.py
Logged in as joshdun (274651796033634304).
Traceback (most recent call last):
  File "C:\Users\sixpa\Downloads\Compressed\Online-Forever-main\filename.py", line 78, in <module>
    run_onliner()
  File "C:\Users\sixpa\Downloads\Compressed\Online-Forever-main\filename.py", line 75, in run_onliner
    onliner(usertoken, status)
  File "C:\Users\sixpa\Downloads\Compressed\Online-Forever-main\filename.py", line 26, in onliner
    ws = websocket.WebSocket()
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
PS C:\Users\sixpa\Downloads\Compressed\Online-Forever-main>

**Comment by SealedSaucer** [comment]
It's already mentioned in the README.md file: [Link](https://github.com/SealedSaucer/Online-Forever#replit-typeerror-websocket__init-missing-3-required-positional-arguments-environ-socket-and-rfile).

Do `pip install websocket-client` in shell and rerun the repl.

**Comment by SealedSaucer** [comment]
Closing the issue.

**Comment by asdat3** [comment]
Hey, I have the module installed, (also via the requirements.txt) but I am getting the same error
`TypeError: __init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'`

There seems to be a Module called "websocket" if you have that installed it will always import it instead of the "websocket-client"
The following should be self explaning but if anyone has this issue and doesn understand python at all do this:

```
pip uninstall websocket
pip install websocket-client
```
> keep in mind on some linux systems you have to use `pip3`
